

package vista;

import controlador.ControladorCliente;
import controlador.ControladorFD;
import controlador.ControladorServicio;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Detalle;
import modelo.Factura;
import modelo.Servicio;

/**
 *
 * @author Andy
 */
public class JF_Factura extends javax.swing.JFrame {
    /**
     * Creates new form Factura
     */
    ControladorFD modelFD=new ControladorFD();
           Factura fUNI=new Factura();
    ControladorCliente modelCli= new ControladorCliente();
           Cliente cUNI=new Cliente(); // CLIENTE UNIVERSAL
    ControladorServicio modelSer= new ControladorServicio();
           Servicio sUNI=new Servicio();
           Detalle dUNI= new Detalle();
    DefaultTableModel tableModel=new DefaultTableModel();
    int Item=0;
    double Totalpagar=0;
    int changeid=0;
    public JF_Factura() {
        initComponents();
        this.setLocationRelativeTo(null);
        Calendar calendar = new GregorianCalendar();
        txtfecha.setText("" + calendar.get(Calendar.YEAR) + 
                "-" + (calendar.get(Calendar.MONTH)+1) +
                "-" + calendar.get(Calendar.DAY_OF_MONTH));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtfecha = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        REGISTRAR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBfactura = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DELETE = new javax.swing.JButton();
        INGRESS = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        changePRICE = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRUC = new javax.swing.JTextField();
        txtNomServicio = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        resultadoEmpleado = new javax.swing.JLabel();
        LABELEMPLEADO = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 150, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DIA:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 556, 50, 30));

        REGISTRAR.setText("REGISTRAR");
        REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRARActionPerformed(evt);
            }
        });
        jPanel1.add(REGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setText("Nombre y apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 250, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setText("FACTURA DE HOSPEDAJE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("DNI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDNIKeyPressed(evt);
            }
        });
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, -1));

        TBfactura.setBackground(new java.awt.Color(153, 153, 153));
        TBfactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "id", "nom_servicio", "RUC", "Precio"
            }
        ));
        TBfactura.setOpaque(false);
        jScrollPane1.setViewportView(TBfactura);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 810, 280));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Cliente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setText("RUC");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setText("Nombre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setText("Precio");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        DELETE.setBackground(new java.awt.Color(255, 51, 51));
        DELETE.setForeground(new java.awt.Color(255, 255, 255));
        DELETE.setText("X");
        DELETE.setBorder(null);
        DELETE.setDefaultCapable(false);
        DELETE.setRequestFocusEnabled(false);
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 60, 30));

        INGRESS.setBackground(new java.awt.Color(51, 255, 51));
        INGRESS.setForeground(new java.awt.Color(255, 255, 255));
        INGRESS.setText("✔");
        INGRESS.setBorder(null);
        INGRESS.setDefaultCapable(false);
        INGRESS.setRequestFocusEnabled(false);
        INGRESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESSActionPerformed(evt);
            }
        });
        jPanel1.add(INGRESS, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 60, 30));

        jLabel9.setText("PRECIO TOTAL:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, -1, 20));

        changePRICE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changePRICE.setText("--------------");
        jPanel1.add(changePRICE, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 80, 20));

        jLabel11.setText("S/.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(java.awt.Color.lightGray);
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("_");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 50, 30));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 50, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 30));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Servicios");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 110, 130, 30));

        txtRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRUCKeyPressed(evt);
            }
        });
        jPanel4.add(txtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, -1));
        jPanel4.add(txtNomServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 140, -1));
        jPanel4.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 180, 20));

        resultadoEmpleado.setText("-------------------");
        jPanel4.add(resultadoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        LABELEMPLEADO.setText("Empleado:");
        jPanel4.add(LABELEMPLEADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 70, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 810, 140));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fidelizacion_hotel-lujo.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 860, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER ) {
           
            if (!"".equals(txtDNI.getText())) {
                String DNI=this.txtDNI.getText();
                cUNI = modelCli.buscarDNI(DNI);
                this.txtNombre.setText(cUNI.getNombre()+" "+cUNI.getApellido()); 
                }else{
                JOptionPane.showMessageDialog(this, "porfavor ingrese un DNI");
            }
            }
    }//GEN-LAST:event_txtDNIKeyPressed

    private void txtRUCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRUCKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if (!"".equals(txtRUC.getText())) {
                String RUC=this.txtRUC.getText();
                sUNI = modelSer.buscarServicio(RUC);
                this.txtNomServicio.setText(sUNI.getNom_serv());
                this.txtPrecio.setText(""+sUNI.getPrecio());
                changeid=sUNI.getId();
            }else{
                JOptionPane.showMessageDialog(this, "porfavor ingrese el ruc del servicio");
            }
        }
    }//GEN-LAST:event_txtRUCKeyPressed

    private void INGRESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESSActionPerformed
        // TODO add your handling code here:
       if (!"".equals(txtNomServicio.getText()) &&!"".equals(txtPrecio.getText())) {
            String nombre,ruc;
        Double precio;
        nombre=this.txtNomServicio.getText();
        ruc=this.txtRUC.getText();
        precio=Double.parseDouble(this.txtPrecio.getText());
        tableModel=(DefaultTableModel) TBfactura.getModel();
        Item++;
         ArrayList lista = new ArrayList();
         lista.add(Item);
         lista.add(changeid);
         lista.add(nombre);
         lista.add(ruc);
         lista.add(precio);
                    Object[] O = new Object[5];
                    O[0] = lista.get(0);
                    O[1] = lista.get(1);
                    O[2] = lista.get(2);
                    O[3] = lista.get(3);
                    O[4] = lista.get(4);
                    tableModel.addRow(O);
                    TBfactura.setModel(tableModel);
                    TotalPagar();
        vaciarServicio();
        }else{
            JOptionPane.showMessageDialog(this,"LLENA LOS CAMPOS FALTANTES");
        }
        
    }//GEN-LAST:event_INGRESSActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRARActionPerformed
        // TODO add your handling code here:
        REGISTRARFACTURA();
        REGISTRARDETALLE();
        vaciarTodo();

        for (int i = 0; i < tableModel.getRowCount(); i++) {
            tableModel.removeRow(0);
        }
        this.changePRICE.setText("--------------");
    }//GEN-LAST:event_REGISTRARActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        tableModel=(DefaultTableModel) this.TBfactura.getModel();
        tableModel.removeRow(TBfactura.getSelectedRow());
        TotalPagar();
        txtRUC.requestFocus();
    }//GEN-LAST:event_DELETEActionPerformed
    
    private void TotalPagar() {
        Totalpagar = 0.00;
        int numFila = TBfactura.getRowCount();
        for (int i = 0; i < numFila; i++) {
            double cal = Double.parseDouble(String.valueOf(TBfactura.getModel().getValueAt(i, 4)));
            Totalpagar = Totalpagar + cal;
        }
        changePRICE.setText(String.format("%.2f", Totalpagar));
    }
    
    public void vaciarServicio(){
        this.txtNomServicio.setText("");
        this.txtRUC.setText("");
        this.txtPrecio.setText("");
        this.txtRUC.requestFocus();
    }
    public void vaciarTodo(){
        this. txtDNI.setText("");
        this.txtNombre.setText("");
        this.txtNomServicio.setText("");
        this.txtRUC.setText("");
        this.txtPrecio.setText("");
        tableModel=(DefaultTableModel) this.TBfactura.getModel();
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            tableModel.removeRow(0);
        }
        this.txtDNI.requestFocus();
    }
    
    public void REGISTRARFACTURA(){
        String Nombre=txtNombre.getText();
        String Empleado=JF_Factura.resultadoEmpleado.getText();
        double Monto=Double.parseDouble(changePRICE.getText());
        String fecha=txtfecha.getText();
        Factura RF= new Factura();
        RF.setNombre_cli(Nombre);
        RF.setNombre_emp(Empleado);
        RF.setPrecio_total(Monto);
        RF.setFecha(fecha);
        modelFD.INSERTVENTA(RF);
    }
    public void REGISTRARDETALLE(){
        int id=modelFD.IdFactura();
        for (int i = 0; i <TBfactura.getModel().getRowCount(); i++) {
            int id_serv=Integer.parseInt(TBfactura.getModel().getValueAt(i,1).toString());
            double precio=Double.parseDouble(TBfactura.getModel().getValueAt(i, 4).toString());
            dUNI.setServicio(id_serv);
            dUNI.setPrecio(precio);
            dUNI.setId_factura(id);
            modelFD.INSERTARDETALLE(dUNI);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETE;
    private javax.swing.JButton INGRESS;
    private javax.swing.JLabel LABELEMPLEADO;
    private javax.swing.JButton REGISTRAR;
    private javax.swing.JTable TBfactura;
    private javax.swing.JLabel changePRICE;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel resultadoEmpleado;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNomServicio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtfecha;
    // End of variables declaration//GEN-END:variables
}
